version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt

conda:
  environment: environment.yaml

sphinx:
  configuration: docs/source/conf.py