name: ancient-language-processing
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - opencv
  - pytorch
  - torchvision
  - transformers
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - recommonmark
  - pip
  - pip:
      - sphinx
      - sphinx-rtd-theme
      - fastapi
      - uvicorn